#pragma once

#include <cstdint>

class ITexture;
class KeyValues;

using MaterialVarHandle_t = std::int16_t;

class IMaterial
{
public:
	virtual const char * GetName() const = 0; // 0
	virtual const char * GetTextureGroupName() const = 0; // 1
	virtual const char * ReturnNull2() const = 0; // 2
	virtual int GetMaterialData(void *outData) = 0; // 3
	virtual int GetMappingWidth() = 0; // 4
	virtual int GetMappingHeight() = 0; // 5
	virtual int GetNumAnimationFrames() = 0; // 6
	virtual void GetMaterialOffsetAndScale(float *offset, float *scale) = 0; // 7
	virtual IMaterial * GetMaterialPage() = 0; // 8
	virtual IMaterial * GetRealTimeVersion() = 0; // 9
	virtual void IncrementReferenceCount() = 0; // 10
	virtual void DecrementReferenceCount() = 0; // 11
	virtual void NullSub12() = 0; // 12
	virtual void NullSub13() = 0; // 13
	virtual int GetEnumerationID() const = 0; // 14
	virtual void NullSub15() = 0; // 15
	virtual bool MatchesMaterialTypeMask(std::uint32_t materialTypeMask) const = 0; // 16
	virtual bool IsTranslucent() const = 0; // 17
	virtual bool IsTranslucentForPass(int pass) const = 0; // 18
	virtual bool UsesVertexColor() const = 0; // 19
	virtual bool IsAlphaTested() const = 0; // 20
	virtual bool IsVertexLit() const = 0; // 21
	virtual bool ReturnFalse22() const = 0; // 22
	virtual void * GetRenderState(int pass) = 0; // 23
	virtual IMaterial * GetColorPassMaterial() = 0; // 24
	virtual void * GetShaderSet() = 0; // 25
	virtual bool HasProxy() = 0; // 26
	virtual bool ReturnFalse27() const = 0; // 27
	virtual bool UsesEnvCubemap() const = 0; // 28
	virtual bool ReturnTrue29() const = 0; // 29
	virtual bool ReturnFalse30() const = 0; // 30
	virtual bool ReturnFalse31() const = 0; // 31
	virtual bool ReturnFalse32() const = 0; // 32
	virtual bool ReturnTrue33() const = 0; // 33
	virtual void AlphaModulate(float alpha) = 0; // 34
	virtual void ColorModulate(float red, float green, float blue) = 0; // 35
	virtual void SetMaterialVarFlag(int flag, bool enabled) = 0; // 36
	virtual bool GetMaterialVarFlag(int flag) const = 0; // 37
	virtual bool GetPropertyFlag(int property) = 0; // 38
	virtual bool ReturnTrue39() const = 0; // 39
	virtual bool HasShaderFeatureFlag2() const = 0; // 40
	virtual bool ReturnFalse41() const = 0; // 41
	virtual bool ReturnFalse42() const = 0; // 42
	virtual bool IsDebugMaterial() const = 0; // 43
	virtual bool IsDecal() const = 0; // 44
	virtual bool HasAlphaTestMaterialFlag() const = 0; // 45
	virtual bool HasCompileFlagBit21() const = 0; // 46
	virtual bool HasCompileBlockLOS() const = 0; // 47
	virtual bool HasCompileFlagBit23() const = 0; // 48
	virtual bool HasCompileFlagBit24() const = 0; // 49
	virtual bool HasCompileClip() const = 0; // 50
	virtual bool HasCompileDetail() const = 0; // 51
	virtual bool HasCompileNoDraw() const = 0; // 52
	virtual bool HasCompileNoLight() const = 0; // 53
	virtual bool HasCompileNonSolid() const = 0; // 54
	virtual bool HasCompileNoShadows() const = 0; // 55
	virtual bool HasCompileNpcClip() const = 0; // 56
	virtual bool HasCompilePassBullets() const = 0; // 57
	virtual bool HasCompileFlagBit25() const = 0; // 58
	virtual bool HasCompileSkip() const = 0; // 59
	virtual bool HasCompileSky() const = 0; // 60
	virtual bool HasCompileTrigger() const = 0; // 61
	virtual bool HasCompileWater() const = 0; // 62
	virtual bool HasNoClimb() const = 0; // 63
	virtual bool HasNoGrapple() const = 0; // 64
	virtual bool HasNoToolTexture() const = 0; // 65
	virtual bool IsOperatorFloor() const = 0; // 66
	virtual bool IsPlayerClip() const = 0; // 67
	virtual bool IsPlayerClipHuman() const = 0; // 68
	virtual bool IsPlayerClipTitan() const = 0; // 69
	virtual bool IsPlayerClipOperator() const = 0; // 70
	virtual bool HasCompileFlagBit20() const = 0; // 71
	virtual int GetNumPasses() = 0; // 72
	virtual int GetTextureMemoryBytes() = 0; // 73
	virtual void Refresh() = 0; // 74
	virtual void Precache() = 0; // 75
	virtual bool IsPrecached() = 0; // 76
	virtual void NullSub77() = 0; // 77
	virtual bool IsErrorMaterial() const = 0; // 78
	virtual float GetAlphaModulation() = 0; // 79
	virtual void GetColorModulation(float *color) = 0; // 80
	virtual void SetShaderAndParams(KeyValues *keyValues) = 0; // 81
	virtual const char * GetShaderName() const = 0; // 82
	virtual void DeleteIfUnreferenced() = 0; // 83
	virtual bool IsSpriteCard() = 0; // 84
	virtual void CallBindProxy(void *proxyData) = 0; // 85
	virtual void GetStreamingTextureHandles(void **handles, std::uint32_t *count) = 0; // 86
	virtual const char * GetSurfaceProperty(int surfaceIndex) = 0; // 87
	virtual MaterialVarHandle_t FindVarIndex(const char *name, int type, bool complain) = 0; // 88
	virtual MaterialVarHandle_t ReturnInvalidVarIndex89() = 0; // 89
	virtual MaterialVarHandle_t FindVarFast(const char *name, int type, void *token) = 0; // 90
	virtual MaterialVarHandle_t ReturnInvalidVarIndex91(int type) = 0; // 91
	virtual MaterialVarHandle_t FindNextVar(int type, MaterialVarHandle_t start) = 0; // 92
	virtual const char * GetVarName(MaterialVarHandle_t handle) = 0; // 93
	virtual bool IsVarDefined(MaterialVarHandle_t handle) = 0; // 94
	virtual ITexture * GetTextureValue(MaterialVarHandle_t handle) = 0; // 95
	virtual void * GetRawVarValue(MaterialVarHandle_t handle) = 0; // 96
	virtual int GetIntValue(MaterialVarHandle_t handle) = 0; // 97
	virtual float GetFloatValue(MaterialVarHandle_t handle) = 0; // 98
	virtual void * GetVarValueAddress(MaterialVarHandle_t handle) = 0; // 99
	virtual void GetVec2Value(MaterialVarHandle_t handle, float *value) = 0; // 100
	virtual void GetVec3Value(MaterialVarHandle_t handle, float *value) = 0; // 101
	virtual void GetVec4Value(MaterialVarHandle_t handle, float *value) = 0; // 102
	virtual const char * GetStringValue(MaterialVarHandle_t handle) = 0; // 103
	virtual int GetVarType(MaterialVarHandle_t handle) = 0; // 104
	virtual void SetVarUndefined(MaterialVarHandle_t handle) = 0; // 105
	virtual void SetStringValue(MaterialVarHandle_t handle, const char *value) = 0; // 106
	virtual void SetTextureValue(MaterialVarHandle_t handle, ITexture *value) = 0; // 107
	virtual void SetMaterialValue(MaterialVarHandle_t handle, IMaterial *value) = 0; // 108
	virtual void SetIntValue(MaterialVarHandle_t handle, int value) = 0; // 109
	virtual void SetFloatValue(MaterialVarHandle_t handle, float value) = 0; // 110
	virtual void SetVec2ValueFromArray(MaterialVarHandle_t handle, const float *value) = 0; // 111
	virtual void SetVec2Value(MaterialVarHandle_t handle, float x, float y) = 0; // 112
	virtual void SetVec3ValueFromArray(MaterialVarHandle_t handle, const float *value) = 0; // 113
	virtual void SetVec3Value(MaterialVarHandle_t handle, float x, float y, float z) = 0; // 114
	virtual void SetVec4ValueFromArray(MaterialVarHandle_t handle, const float *value) = 0; // 115
	virtual void SetVec4Value(MaterialVarHandle_t handle, float x, float y, float z, float w) = 0; // 116
	virtual void SetMatrixValue(MaterialVarHandle_t handle, const float *matrix4x4) = 0; // 117
	virtual void NullSub118(MaterialVarHandle_t handle, ITexture *value) = 0; // 118
	virtual void NullSub119(MaterialVarHandle_t handle, int value) = 0; // 119
	virtual void NullSub120(MaterialVarHandle_t handle, float value) = 0; // 120
	virtual void NullSub121(IMaterial *sourceMaterial) = 0; // 121
	virtual int GetReferenceCount() const = 0; // 122
	virtual int GetUsageReferenceCount() const = 0; // 123
	virtual void NullSub124(int enumerationId) = 0; // 124
	virtual void NullSub125() = 0; // 125
	virtual void NullSub126() = 0; // 126
	virtual bool ReturnFalse127() = 0; // 127
	virtual void NullSub128() = 0; // 128
	virtual void * GetShader() const = 0; // 129
	virtual bool ReturnTrue130() const = 0; // 130
	virtual bool ReturnTrue131() const = 0; // 131
	virtual bool GetRenderStateForPass(unsigned int pass, int excludedFlags, void *outState) = 0; // 132
	virtual int ReturnZero133(void *outState) = 0; // 133
	virtual void * GetShaderInterface() const = 0; // 134
	virtual void ToggleSuppression() = 0; // 135
	virtual bool IsSuppressed() const = 0; // 136
	virtual void GetDiffuseModulation(float *color) const = 0; // 137
	virtual void GetReflectivity(float *reflectivity) const = 0; // 138
	virtual void * ReturnNull139() = 0; // 139
	virtual void NullSub140() = 0; // 140
	virtual void NullSub141() = 0; // 141
	virtual bool ReturnFalse142() const = 0; // 142
	virtual void NullSub143() = 0; // 143
	virtual std::uint32_t ReturnZero144() const = 0; // 144
};
static_assert(sizeof(IMaterial) == sizeof(void*));
