#include "modsystem/modmanager.h"
#include "core/filesystem/filesystem.h"
#include "shared/keyvalues.h"
#include "tier0/vanilla.h"

#include <algorithm>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string_view>

static void WriteKeyValuesIndent(std::ostream& output, const size_t depth)
{
	for (size_t i = 0; i < depth; ++i)
		output << '\t';
}

static void WriteEscapedKeyValuesString(std::ostream& output, const std::string_view value)
{
	for (const char character : value)
	{
		if (character == '"')
			output << "\\\"";
		else if (character == '\r')
			output << "\\r";
		else if (character == '\n')
			output << "\\n";
		else
			output << character;
	}
}

static void WriteResolvedKeyValues(std::ostream& output, const KeyValues& keyValues, const size_t depth)
{
	WriteKeyValuesIndent(output, depth);
	output << '"';
	WriteEscapedKeyValuesString(output, keyValues.GetName() ? keyValues.GetName() : "");
	output << '"';

	if (keyValues.m_pSub || keyValues.GetDataType() == TYPE_NONE)
	{
		output << "\n";
		WriteKeyValuesIndent(output, depth);
		output << "{\n";

		for (const KeyValues* child = keyValues.m_pSub; child; child = child->m_pPeer)
			WriteResolvedKeyValues(output, *child, depth + 1);

		WriteKeyValuesIndent(output, depth);
		output << "}\n";
		return;
	}

	output << "\t\t\"";
	WriteEscapedKeyValuesString(output, keyValues.GetStringValue());
	output << "\"\n";
}

static bool IsSafeKeyValuesDumpPath(const fs::path& path)
{
	if (path.empty() || path.is_absolute())
		return false;

	return std::ranges::none_of(path, [](const fs::path& component) { return component == ".."; });
}

static bool WriteKeyValuesOrderBase(
	const fs::path& outputPath, const std::string& resourceName, const std::string& originalContents, const char* rootName)
{
	if (strcmp(rootName, "WeaponData"))
		return false;

	KeyValues originalKeyValues(resourceName.c_str());
	if (!KeyValues_LoadFromBuffer(&originalKeyValues, resourceName.c_str(), originalContents.c_str(), g_pFilesystem))
	{
		spdlog::warn("Could not parse original KeyValues file {} to preserve weapon mod order.", resourceName);
		return false;
	}

	KeyValues* mods = originalKeyValues.FindKey("Mods");
	if (!mods || !mods->m_pSub)
		return false;

	std::ofstream output(outputPath, std::ios::binary | std::ios::trunc);
	if (!output)
	{
		spdlog::warn("Could not write weapon mod order base {}.", outputPath.string());
		return false;
	}

	output << "// AUTOGENERATED: SELECTED BASE WEAPON MOD ORDER\n\"";
	WriteEscapedKeyValuesString(output, rootName);
	output << "\"\n{\n\t\"Mods\"\n\t{\n";

	for (const KeyValues* weaponMod = mods->m_pSub; weaponMod; weaponMod = weaponMod->m_pPeer)
	{
		output << "\t\t\"";
		WriteEscapedKeyValuesString(output, weaponMod->GetName() ? weaponMod->GetName() : "");
		output << "\"\n\t\t{\n\t\t}\n";
	}

	output << "\t}\n}\n";
	return output.good();
}

void ModManager::ProcessConditionalBlocks(const fs::path& filePath, bool keepNorthstar)
{
	std::ifstream inFile(filePath, std::ios::binary);
	if (!inFile)
		return;

	std::ostringstream processed;
	std::string line;
	bool inConditional = false;
	bool keepBlock = true;

	while (std::getline(inFile, line))
	{
		if (!line.empty() && line.back() == '\r')
			line.pop_back();

		if (line.find("///if VANILLA") != std::string::npos)
		{
			inConditional = true;
			keepBlock = !keepNorthstar;
			continue;
		}
		else if (line.find("///if NORTHSTAR") != std::string::npos)
		{
			inConditional = true;
			keepBlock = keepNorthstar;
			continue;
		}
		else if (line.find("///endif") != std::string::npos)
		{
			inConditional = false;
			keepBlock = true;
			continue;
		}

		if (!inConditional || keepBlock)
			processed << line << "\n";
	}
	inFile.close();

	std::ofstream outFile(filePath, std::ios::binary | std::ios::trunc);
	outFile << processed.str();
	outFile.close();
}

void ModManager::RegisterCompiledKeyValuesFiles(const char* filename, const ModOverrideFile& modFile)
{
	const fs::path kvPath(filename);
	const fs::path kvDirectory = kvPath.parent_path();

	// KeyValues opens every #base through the filesystem independently. Mark
	// each generated dependency so it cannot resolve against a stale mod path.
	m_CompiledFiles.insert(NormaliseModFilePath(kvPath));
	m_CompiledFiles.insert(NormaliseModFilePath(kvDirectory / ("mod_original_" + kvPath.filename().string())));

	if (!modFile.m_KeyValuesOrderPath.empty())
		m_CompiledFiles.insert(NormaliseModFilePath(kvDirectory / modFile.m_KeyValuesOrderPath));

	for (const std::string& patchPath : modFile.m_VanillaKeyvaluePaths)
		m_CompiledFiles.insert(NormaliseModFilePath(kvDirectory / patchPath));

	for (const std::string& patchPath : modFile.m_NorthstarKeyvaluePaths)
		m_CompiledFiles.insert(NormaliseModFilePath(kvDirectory / patchPath));
}

void ModManager::DumpCompiledKeyValues()
{
	std::vector<std::string> keyValuesPaths;
	for (const Mod& mod : m_LoadedMods)
	{
		if (!mod.m_bEnabled)
			continue;

		for (const auto& [fileHash, path] : mod.KeyValues)
		{
			NOTE_UNUSED(fileHash);
			keyValuesPaths.push_back(path);
		}
	}

	std::ranges::sort(keyValuesPaths);
	keyValuesPaths.erase(std::unique(keyValuesPaths.begin(), keyValuesPaths.end()), keyValuesPaths.end());

	for (const std::string& path : keyValuesPaths)
		CompileAssetsForFile(path.c_str());

	const fs::path dumpDirectory = GetCompiledAssetsPath().parent_path() / "compiled_keyvalues_dump";
	std::error_code error;
	fs::remove_all(dumpDirectory, error);
	if (error)
	{
		spdlog::error("Failed to clear compiled KeyValues dump directory {}: {}", dumpDirectory.string(), error.message());
		return;
	}

	fs::create_directories(dumpDirectory, error);
	if (error)
	{
		spdlog::error("Failed to create compiled KeyValues dump directory {}: {}", dumpDirectory.string(), error.message());
		return;
	}

	size_t dumpedFiles = 0;
	size_t failedFiles = 0;
	for (const auto& [normalisedPath, compiledFile] : m_CompiledAssetFiles)
	{
		NOTE_UNUSED(normalisedPath);

		const fs::path relativePath = compiledFile.m_Path;
		if (!IsSafeKeyValuesDumpPath(relativePath))
		{
			spdlog::warn("Refusing to dump compiled KeyValues with unsafe path {}.", relativePath.string());
			++failedFiles;
			continue;
		}

		const fs::path compiledPath = GetCompiledAssetsPath() / relativePath;
		std::ifstream input(compiledPath, std::ios::binary);
		if (!input)
		{
			spdlog::warn("Could not read compiled KeyValues file {}.", compiledPath.string());
			++failedFiles;
			continue;
		}

		std::ostringstream buffer;
		buffer << input.rdbuf();
		const std::string compiledContents = buffer.str();

		const std::string resourceName = relativePath.generic_string();
		KeyValues resolvedKeyValues(resourceName.c_str());
		const bool loaded =
			KeyValues_LoadFromBuffer(&resolvedKeyValues, resourceName.c_str(), compiledContents.c_str(), g_pFilesystem);
		const char* resolvedRootName = resolvedKeyValues.GetName();
		if (!loaded || !resolvedRootName || !resolvedRootName[0])
		{
			spdlog::warn("Could not resolve #base files for compiled KeyValues file {}.", resourceName);
			++failedFiles;
			continue;
		}

		const fs::path outputPath = dumpDirectory / relativePath;
		fs::create_directories(outputPath.parent_path(), error);
		if (error)
		{
			spdlog::warn("Could not create compiled KeyValues dump directory {}: {}", outputPath.parent_path().string(), error.message());
			error.clear();
			++failedFiles;
			continue;
		}

		std::ofstream output(outputPath, std::ios::binary | std::ios::trunc);
		if (!output)
		{
			spdlog::warn("Could not write resolved KeyValues file {}.", outputPath.string());
			++failedFiles;
			continue;
		}

		output << "// AUTOGENERATED: RESOLVED COMPILED KEYVALUES\n";
		for (const KeyValues* root = &resolvedKeyValues; root; root = root->m_pPeer)
			WriteResolvedKeyValues(output, *root, 0);
		++dumpedFiles;
	}

	spdlog::info(
		"Dumped {} resolved compiled KeyValues files to {} ({} failed).", dumpedFiles, dumpDirectory.string(), failedFiles);
}

void ModManager::TryChangeoverKeyValues(const char* filename, ModOverrideFile& modFile)
{
	if (g_pVanillaCompatibility->GetVanillaCompatibility() ==
		(modFile.m_lastCompatibilityMode == VanillaCompatibility::CompatibilityMode::Vanilla))
		return;

	spdlog::info("Trying to changeover KeyValues for file {}", filename);

	fs::path compiledPath = GetCompiledAssetsPath() / filename;
	fs::path compiledDir = compiledPath.parent_path();

	if (modFile.m_KeyValuesRootName.empty())
	{
		spdlog::warn("Cannot change over KeyValues file {} because its root name is missing.", filename);
		return;
	}

	modFile.m_lastCompatibilityMode = g_pVanillaCompatibility->GetVanillaCompatibility()
										  ? VanillaCompatibility::CompatibilityMode::Vanilla
										  : VanillaCompatibility::CompatibilityMode::Northstar;

	std::ofstream writeStream(compiledPath, std::ios::binary);

	constexpr std::string_view generatedHeader = "// AUTOGENERATED: MOD PATCH KV\n";
	std::string newKvs(generatedHeader);

	std::vector<std::string>& patchesVec =
		g_pVanillaCompatibility->GetVanillaCompatibility() ? modFile.m_VanillaKeyvaluePaths : modFile.m_NorthstarKeyvaluePaths;

	fs::path kvPath(filename);
	std::string ogFilePath = "mod_original_";
	ogFilePath += kvPath.filename().string();

	if (!modFile.m_KeyValuesOrderPath.empty() && fs::exists(compiledDir / modFile.m_KeyValuesOrderPath))
	{
		newKvs += "#base \"";
		newKvs += modFile.m_KeyValuesOrderPath;
		newKvs += "\"\n";
	}

	for (auto& patchFilePath : patchesVec)
	{
		if (fs::exists(compiledDir / patchFilePath))
		{
			newKvs += "#base \"";
			newKvs += patchFilePath;
			newKvs += "\"\n";
		}
		else
		{
			spdlog::warn("Patch file {} does not exist, skipping.", patchFilePath);
			continue;
		}
	}

	newKvs += "#base \"";
	newKvs += ogFilePath;
	newKvs += "\"\n";
	newKvs += modFile.m_KeyValuesRootName;
	newKvs += "\n{\n}\n";

	writeStream << newKvs;
	writeStream.close();
}

void ModManager::TryBuildKeyValues(const char* filename)
{
	spdlog::info("Building KeyValues for file {}", filename);

	std::string normalisedPath = g_pModManager->NormaliseModFilePath(fs::path(filename));
	fs::path compiledPath = GetCompiledAssetsPath() / filename;
	fs::path compiledDir = compiledPath.parent_path();
	fs::create_directories(compiledDir);

	fs::path kvPath(filename);
	std::string ogFilePath = "mod_original_";
	ogFilePath += kvPath.filename().string();

	constexpr std::string_view generatedHeader = "// AUTOGENERATED: MOD PATCH KV\n";
	std::string newKvs(generatedHeader);

	int patchNum = 0;

	ModOverrideFile overrideFile;

	// copy over patch kv files, and add #bases to new file, last mods' patches should be applied first
	// note: #include should be identical but it's actually just broken, thanks respawn
	for (int64_t i = m_LoadedMods.size() - 1; i > -1; i--)
	{
		if (!m_LoadedMods[i].m_bEnabled)
			continue;

		size_t fileHash = STR_HASH(normalisedPath);
		auto modKv = m_LoadedMods[i].KeyValues.find(fileHash);
		if (modKv != m_LoadedMods[i].KeyValues.end())
		{
			// should result in smth along the lines of #include "mod_patch_5_mp_weapon_car.txt"

			constexpr const char* patchPrefix = "mod_patch_";
			patchNum++;

			std::string vanillaPatchPath = std::string(patchPrefix) + std::to_string(patchNum++) + "_v_" + kvPath.filename().string();
			std::string northstarPatchPath = std::string(patchPrefix) + std::to_string(patchNum++) + "_n_" + kvPath.filename().string();
			std::string& patchFilePath = (g_pVanillaCompatibility->GetVanillaCompatibility() ? vanillaPatchPath : northstarPatchPath);

			newKvs += "#base \"";
			newKvs += patchFilePath;
			newKvs += "\"\n";

			overrideFile.m_VanillaKeyvaluePaths.push_back(vanillaPatchPath);
			overrideFile.m_NorthstarKeyvaluePaths.push_back(northstarPatchPath);

			fs::remove(compiledDir / vanillaPatchPath);
			fs::remove(compiledDir / northstarPatchPath);

			fs::copy_file(m_LoadedMods[i].m_ModDirectory / "keyvalues" / filename, compiledDir / vanillaPatchPath);
			fs::copy_file(m_LoadedMods[i].m_ModDirectory / "keyvalues" / filename, compiledDir / northstarPatchPath);

			ProcessConditionalBlocks(compiledDir / vanillaPatchPath, false);
			ProcessConditionalBlocks(compiledDir / northstarPatchPath, true);
		}
	}

	// add original #base last, #bases don't override preexisting keys, including the ones we've just done
	newKvs += "#base \"";
	newKvs += ogFilePath;
	newKvs += "\"\n";

	// load original file, so we can parse out the name of the root obj (e.g. WeaponData for weapons)
	std::string originalFile = ReadVPKFile(filename, FileSourceType_ModOverride | FileSourceType_Original);

	if (!originalFile.length())
	{
		spdlog::warn("Tried to patch kv {} but no base kv was found!", ogFilePath);
		return;
	}

	char rootName[64];
	memset(rootName, 0, sizeof(rootName));

	// iterate until we hit an ascii char that isn't in a # command or comment to get root obj name
	int i = 0;
	while (!(originalFile[i] >= 65 && originalFile[i] <= 122))
	{
		// if we hit a comment or # thing, iterate until end of line
		if (originalFile[i] == '/' || originalFile[i] == '#')
			while (originalFile[i] != '\n')
				i++;

		i++;
	}

	int j = 0;
	for (int j = 0; originalFile[i] >= 65 && originalFile[i] <= 122; j++)
		rootName[j] = originalFile[i++];

	// empty kv, all the other stuff gets #base'd
	newKvs += rootName;
	newKvs += "\n{\n}\n";

	std::ofstream originalFileWriteStream(compiledDir / ogFilePath, std::ios::binary);
	originalFileWriteStream << originalFile;
	originalFileWriteStream.close();

	const std::string orderFilePath = "mod_order_" + kvPath.filename().string();
	fs::remove(compiledDir / orderFilePath);
	if (WriteKeyValuesOrderBase(compiledDir / orderFilePath, ogFilePath, originalFile, rootName))
	{
		// #base only appends missing nodes. Seed the selected base's order before
		// sparse patches so overriding Mods entries cannot move their indices.
		overrideFile.m_KeyValuesOrderPath = orderFilePath;
		newKvs.insert(generatedHeader.size(), "#base \"" + orderFilePath + "\"\n");
	}

	std::ofstream writeStream(compiledPath, std::ios::binary);
	writeStream << newKvs;
	writeStream.close();

	overrideFile.m_pOwningMod = nullptr;
	overrideFile.m_Path = normalisedPath;
	overrideFile.m_KeyValuesRootName = rootName;
	overrideFile.m_lastCompatibilityMode = g_pVanillaCompatibility->GetVanillaCompatibility()
											   ? VanillaCompatibility::CompatibilityMode::Vanilla
											   : VanillaCompatibility::CompatibilityMode::Northstar;

	// Compiled wrappers are output files, not mod overrides. Keeping them out of
	// m_ModFiles preserves the real owning mod used when selecting the base file.
	m_CompiledAssetFiles.insert_or_assign(normalisedPath, overrideFile);
	RegisterCompiledKeyValuesFiles(filename, overrideFile);
}
