#pragma once

#include "mathlib/vector.h"
#include "tier1/refcount.h"

#include <cstddef>
#include <cstdint>
#include <type_traits>

inline constexpr std::uint32_t IDSTUDIOHEADER = 0x54534449u; // "IDST"
inline constexpr std::uint32_t MODEL_VERTEX_FILE_ID = 0x56534449u; // "IDSV"
inline constexpr std::int32_t MODEL_VERTEX_FILE_VERSION = 4;
inline constexpr std::uint32_t MODEL_VERTEX_COLOR_FILE_ID = 0x56434449u; // "IDCV"
inline constexpr std::int32_t MODEL_VERTEX_COLOR_FILE_VERSION = 1;
inline constexpr std::int32_t STUDIO_VERSION_TITANFALL2 = 53;
inline constexpr std::size_t MAX_NUM_LODS = 8;
inline constexpr std::size_t MAX_NUM_BONES_PER_VERT = 3;
inline constexpr std::size_t MAXSTUDIOBONES = 256;

// Runtime and file flags stored in studiohdr_t::flags.
enum StudioHeaderFlags : std::uint32_t
{
    STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 1u << 0,
    STUDIOHDR_FLAGS_USES_ENV_CUBEMAP = 1u << 1,
    STUDIOHDR_FLAGS_FORCE_OPAQUE = 1u << 2,
    STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS = 1u << 3,
    STUDIOHDR_FLAGS_STATIC_PROP = 1u << 4,
    STUDIOHDR_FLAGS_USES_FB_TEXTURE = 1u << 5,
    STUDIOHDR_FLAGS_HASSHADOWLOD = 1u << 6,
    STUDIOHDR_FLAGS_USES_BUMPMAPPING = 1u << 7,
    STUDIOHDR_FLAGS_USE_SHADOWLOD_MATERIALS = 1u << 8,
    STUDIOHDR_FLAGS_OBSOLETE = 1u << 9,
    STUDIOHDR_FLAGS_NEEDS_DEFERRED_ADDITIVE = 1u << 10,
    STUDIOHDR_FLAGS_NO_FORCED_FADE = 1u << 11,
    STUDIOHDR_FLAGS_FORCE_PHONEME_CROSSFADE = 1u << 12,
    STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT = 1u << 13,
    STUDIOHDR_FLAGS_COMPLEX_WEIGHTS = 1u << 14,
    STUDIOHDR_FLAGS_BUILT_IN_PREVIEW_MODE = 1u << 15,
    STUDIOHDR_FLAGS_AMBIENT_BOOST = 1u << 16,
    STUDIOHDR_FLAGS_DO_NOT_CAST_SHADOWS = 1u << 17,
    STUDIOHDR_FLAGS_CAST_TEXTURE_SHADOWS = 1u << 18,
    STUDIOHDR_FLAGS_SUBDIVISION_SURFACE = 1u << 19,
    STUDIOHDR_FLAGS_NO_ANIM_EVENTS = 1u << 20,
    STUDIOHDR_FLAGS_VERT_ANIM_FIXED_POINT_SCALE = 1u << 21,
    STUDIOHDR_FLAGS_RESPAWN_UNKNOWN = 1u << 23,
    STUDIOHDR_FLAGS_USES_VERTEX_COLOR = 1u << 24,
    STUDIOHDR_FLAGS_USES_UV2 = 1u << 25,
};

struct studiohdr_t;
struct studiomeshgroup_t;
class IMaterial;

struct mstudiotexture_t
{
    std::int32_t sznameindex;
    std::int32_t unused_flags;
    std::int32_t used;
    std::int32_t unused1;
    std::int32_t material_RESERVED;
    std::int32_t clientmaterial_RESERVED;
    std::int32_t unused[10];

    const char* Name() const noexcept
    {
        return sznameindex > 0 ? reinterpret_cast<const char*>(this) + sznameindex : "";
    }
};

struct mstudio_meshvertexdata_t
{
    std::int32_t modelvertexdata;
    std::int32_t numLODVertexes[MAX_NUM_LODS];
};

#pragma pack(push, 4)
struct mstudiomesh_t
{
    std::int32_t material;
    std::int32_t modelindex;
    std::int32_t numvertices;
    std::int32_t vertexoffset;
    std::int32_t deprecated_numflexes;
    std::int32_t deprecated_flexindex;
    std::int32_t deprecated_materialtype;
    std::int32_t deprecated_materialparam;
    std::int32_t meshid;
    Vector3 center;
    mstudio_meshvertexdata_t vertexloddata;
    void* pUnknown;
    std::int32_t reserved[6];
};
#pragma pack(pop)

struct mstudiomodel_t
{
    char name[64];
    std::int32_t type;
    float boundingradius;
    std::int32_t nummeshes;
    std::int32_t meshindex;
    std::int32_t numvertices;
    std::int32_t vertexindex;
    std::int32_t tangentsindex;
    std::int32_t numattachments;
    std::int32_t attachmentindex;
    std::int32_t deprecated_numeyeballs;
    std::int32_t deprecated_eyeballindex;
    std::int32_t pad[4];
    std::int32_t colorindex;
    std::int32_t uv2index;
    std::int32_t reserved[4];

    const mstudiomesh_t* Mesh(std::size_t index) const noexcept
    {
        if (nummeshes <= 0 || index >= static_cast<std::size_t>(nummeshes) || meshindex <= 0)
            return nullptr;
        return reinterpret_cast<const mstudiomesh_t*>(reinterpret_cast<const std::uint8_t*>(this) + meshindex) + index;
    }
};

struct mstudiobodyparts_t
{
    std::int32_t sznameindex;
    std::int32_t nummodels;
    std::int32_t base;
    std::int32_t modelindex;

    const char* Name() const noexcept
    {
        return sznameindex > 0 ? reinterpret_cast<const char*>(this) + sznameindex : "";
    }

    const mstudiomodel_t* Model(std::size_t index) const noexcept
    {
        if (nummodels <= 0 || index >= static_cast<std::size_t>(nummodels) || modelindex <= 0)
            return nullptr;
        return reinterpret_cast<const mstudiomodel_t*>(reinterpret_cast<const std::uint8_t*>(this) + modelindex) + index;
    }
};

struct studiohdr2_t
{
    std::int32_t numsrcbonetransform;
    std::int32_t srcbonetransformindex;
    std::int32_t illumpositionattachmentindex;
    float flMaxEyeDeflection;
    std::int32_t linearboneindex;
    std::int32_t sznameindex;
    std::int32_t m_nBoneFlexDriverCount;
    std::int32_t m_nBoneFlexDriverIndex;
    std::int32_t m_nPerTriAABBIndex;
    std::int32_t m_nPerTriAABBNodeCount;
    std::int32_t m_nPerTriAABBLeafCount;
    std::int32_t m_nPerTriAABBVertCount;
    std::int32_t unkStringOffset;
    std::int32_t reserved[39];

    const char* Name() const noexcept
    {
        return sznameindex > 0 ? reinterpret_cast<const char*>(this) + sznameindex : "";
    }
};

struct studiohdr_t
{
    std::int32_t id;
    std::int32_t version;
    std::int32_t checksum;
    char name[64];
    std::int32_t length;
    Vector3 eyeposition;
    Vector3 illumposition;
    Vector3 hull_min;
    Vector3 hull_max;
    Vector3 view_bbmin;
    Vector3 view_bbmax;
    std::uint32_t flags;
    std::int32_t numbones;
    std::int32_t boneindex;
    std::int32_t numbonecontrollers;
    std::int32_t bonecontrollerindex;
    std::int32_t numhitboxsets;
    std::int32_t hitboxsetindex;
    std::int32_t numlocalanim;
    std::int32_t localanimindex;
    std::int32_t numlocalseq;
    std::int32_t localseqindex;
    std::int32_t activitylistversion;
    std::int32_t eventsindexed;
    std::int32_t numtextures;
    std::int32_t textureindex;
    std::int32_t numcdtextures;
    std::int32_t cdtextureindex;
    std::int32_t numskinref;
    std::int32_t numskinfamilies;
    std::int32_t skinindex;
    std::int32_t numbodyparts;
    std::int32_t bodypartindex;
    std::int32_t numlocalattachments;
    std::int32_t localattachmentindex;
    std::int32_t numlocalnodes;
    std::int32_t localnodeindex;
    std::int32_t localnodenameindex;
    std::int32_t deprecated_numflexdesc;
    std::int32_t deprecated_flexdescindex;
    std::int32_t deprecated_numflexcontrollers;
    std::int32_t deprecated_flexcontrollerindex;
    std::int32_t deprecated_numflexrules;
    std::int32_t deprecated_flexruleindex;
    std::int32_t numikchains;
    std::int32_t ikchainindex;
    std::int32_t deprecated_nummouths;
    std::int32_t deprecated_mouthindex;
    std::int32_t numlocalposeparameters;
    std::int32_t localposeparamindex;
    std::int32_t surfacepropindex;
    std::int32_t keyvalueindex;
    std::int32_t keyvaluesize;
    std::int32_t numlocalikautoplaylocks;
    std::int32_t localikautoplaylockindex;
    float mass;
    std::int32_t contents;
    std::int32_t numincludemodels;
    std::int32_t includemodelindex;
    std::int32_t virtualModel;
    std::int32_t szanimblocknameindex;
    std::int32_t numanimblocks;
    std::int32_t animblockindex;
    std::int32_t animblockModel;
    std::int32_t bonetablebynameindex;
    std::int32_t pVertexBase;
    std::int32_t pIndexBase;
    std::uint8_t constdirectionallightdot;
    std::uint8_t rootLOD;
    std::uint8_t numAllowedRootLODs;
    std::uint8_t unused;
    float defaultFadeDist;
    std::int32_t deprecated_numflexcontrollerui;
    std::int32_t deprecated_flexcontrolleruiindex;
    float flVertAnimFixedPointScale;
    std::int32_t surfacepropLookup;
    std::int32_t studiohdr2index;
    std::int32_t sourceFilenameOffset;

    const char* Name() const noexcept { return name; }

    const studiohdr2_t* StudioHdr2() const noexcept
    {
        if (studiohdr2index <= 0 || length < 0)
            return nullptr;
        const auto offset = static_cast<std::size_t>(studiohdr2index);
        const auto bytes = static_cast<std::size_t>(length);
        if (offset > bytes || sizeof(studiohdr2_t) > bytes - offset)
            return nullptr;
        return reinterpret_cast<const studiohdr2_t*>(reinterpret_cast<const std::uint8_t*>(this) + offset);
    }

    const char* SourceFilename() const noexcept
    {
        if (sourceFilenameOffset <= 0 || length <= sourceFilenameOffset)
            return "";
        return reinterpret_cast<const char*>(this) + sourceFilenameOffset;
    }

    const mstudiotexture_t* Texture(std::size_t index) const noexcept
    {
        if (numtextures <= 0 || index >= static_cast<std::size_t>(numtextures) || textureindex <= 0 || length < 0)
            return nullptr;
        const auto offset = static_cast<std::size_t>(textureindex);
        const auto bytes = static_cast<std::size_t>(length);
        const auto remaining = bytes >= offset ? bytes - offset : 0;
        if (index >= remaining / sizeof(mstudiotexture_t))
            return nullptr;
        return reinterpret_cast<const mstudiotexture_t*>(reinterpret_cast<const std::uint8_t*>(this) + offset) + index;
    }

    const mstudiobodyparts_t* BodyPart(std::size_t index) const noexcept
    {
        if (numbodyparts <= 0 || index >= static_cast<std::size_t>(numbodyparts) || bodypartindex <= 0 || length < 0)
            return nullptr;
        const auto offset = static_cast<std::size_t>(bodypartindex);
        const auto bytes = static_cast<std::size_t>(length);
        const auto remaining = bytes >= offset ? bytes - offset : 0;
        if (index >= remaining / sizeof(mstudiobodyparts_t))
            return nullptr;
        return reinterpret_cast<const mstudiobodyparts_t*>(reinterpret_cast<const std::uint8_t*>(this) + offset) + index;
    }
};

struct mstudio_boneweight_t
{
    float weight[MAX_NUM_BONES_PER_VERT];
    std::uint8_t bone[MAX_NUM_BONES_PER_VERT];
    std::uint8_t numbones;
};

struct mstudiovertex_t
{
    mstudio_boneweight_t m_BoneWeights;
    Vector3 m_vecPosition;
    Vector3 m_vecNormal;
    Vector2 m_vecTexCoord;
};

struct vertexFileFixup_t
{
    std::int32_t lod;
    std::int32_t sourceVertexID;
    std::int32_t numVertexes;
};

struct vertexFileHeader_t
{
    std::uint32_t id;
    std::int32_t version;
    std::int32_t checksum;
    std::int32_t numLODs;
    std::int32_t numLODVertexes[MAX_NUM_LODS];
    std::int32_t numFixups;
    std::int32_t fixupTableStart;
    std::int32_t vertexDataStart;
    std::int32_t tangentDataStart;

    std::size_t VertexCount(std::size_t lod = 0) const noexcept
    {
        if (numLODs <= 0 || lod >= MAX_NUM_LODS || lod >= static_cast<std::size_t>(numLODs) || numLODVertexes[lod] < 0)
            return 0;
        return static_cast<std::size_t>(numLODVertexes[lod]);
    }

    const vertexFileFixup_t* Fixup(std::size_t index) const noexcept
    {
        if (numFixups <= 0 || index >= static_cast<std::size_t>(numFixups) || fixupTableStart <= 0)
            return nullptr;
        return reinterpret_cast<const vertexFileFixup_t*>(reinterpret_cast<const std::uint8_t*>(this) + fixupTableStart) + index;
    }

    const mstudiovertex_t* Vertex(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || vertexDataStart <= 0)
            return nullptr;
        return reinterpret_cast<const mstudiovertex_t*>(reinterpret_cast<const std::uint8_t*>(this) + vertexDataStart) + index;
    }

    const float* Tangent(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || tangentDataStart <= 0)
            return nullptr;
        return reinterpret_cast<const float*>(reinterpret_cast<const std::uint8_t*>(this) + tangentDataStart) + index * 4;
    }
};

struct studio_color32_t
{
    std::uint8_t r;
    std::uint8_t g;
    std::uint8_t b;
    std::uint8_t a;
};

struct vertexColorFileHeader_t
{
    std::uint32_t id;
    std::int32_t version;
    std::int32_t checksum;
    std::int32_t numLODs;
    std::int32_t numLODVertexes[MAX_NUM_LODS];
    std::int32_t colorDataStart;
    std::int32_t uv2DataStart;

    std::size_t VertexCount(std::size_t lod = 0) const noexcept
    {
        if (numLODs <= 0 || lod >= MAX_NUM_LODS || lod >= static_cast<std::size_t>(numLODs) || numLODVertexes[lod] < 0)
            return 0;
        return static_cast<std::size_t>(numLODVertexes[lod]);
    }

    const studio_color32_t* Color(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || colorDataStart <= 0)
            return nullptr;
        return reinterpret_cast<const studio_color32_t*>(reinterpret_cast<const std::uint8_t*>(this) + colorDataStart) + index;
    }

    const Vector2* SecondaryUV(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || uv2DataStart <= 0)
            return nullptr;
        return reinterpret_cast<const Vector2*>(reinterpret_cast<const std::uint8_t*>(this) + uv2DataStart) + index;
    }
};

struct studiomeshdata_t
{
    std::int32_t m_NumGroup;
    std::uint32_t reservedAlignment;
    studiomeshgroup_t* m_pMeshGroup;
};

struct studioloddata_t
{
    studiomeshdata_t* m_pMeshData;
    float m_SwitchPoint;
    std::int32_t m_NumMaterials;
    IMaterial** m_ppMaterials;
    std::int32_t* m_pMaterialFlags;
    std::int32_t* m_pHWMorphDecalBoneRemap;
    std::int32_t m_DecalBoneCount;
    std::uint32_t reservedAlignment;
};

struct studiohwdata_t
{
    std::int32_t m_RootLOD;
    std::int32_t m_NumLODs;
    studioloddata_t* m_pLODs;
    std::int32_t m_NumStudioMeshes;
    std::int32_t m_NumVertices;
    std::uint8_t* m_pVertexRemap;

    const studioloddata_t* LOD(std::size_t index) const noexcept
    {
        return m_pLODs != nullptr && m_NumLODs > 0 && index < static_cast<std::size_t>(m_NumLODs)
            ? m_pLODs + index
            : nullptr;
    }
};

template <class T>
class CStudioAssetEmbeddedRef : public CRefCounted<>
{
  protected:
    T m_Embedded;
};

class CStudioHWDataRef : public CStudioAssetEmbeddedRef<studiohwdata_t>
{
  public:
    studiohwdata_t* GetHardwareData() noexcept { return &m_Embedded; }
    const studiohwdata_t* GetHardwareData() const noexcept { return &m_Embedded; }
};

template <typename T>
struct studio_utlvector_t
{
    T* m_pMemory;
    std::int64_t m_AllocationCount;
    std::int64_t m_GrowSize;
    std::int32_t m_Size;
    std::uint32_t reservedAlignment;

    const T* Data() const noexcept { return m_pMemory; }
    std::size_t Size() const noexcept { return m_Size > 0 ? static_cast<std::size_t>(m_Size) : 0; }
};

struct virtualsequence_t
{
    std::int32_t flags;
    std::int32_t activity;
    std::int32_t group;
    std::int32_t index;
};

struct virtualgeneric_t
{
    std::int32_t group;
    std::int32_t index;
};

struct virtualgroup_t
{
    void* cache;
    studio_utlvector_t<std::int32_t> boneMap;
    studio_utlvector_t<std::int32_t> masterBone;
    studio_utlvector_t<std::int32_t> masterSeq;
    studio_utlvector_t<std::int32_t> masterAnim;
    studio_utlvector_t<std::int32_t> masterAttachment;
    studio_utlvector_t<std::int32_t> masterPose;
    studio_utlvector_t<std::int32_t> masterNode;
};

struct studio_thread_fast_mutex_t
{
    void* debugInfo;
    std::int32_t lockCount;
    std::int32_t recursionCount;
    void* owningThread;
    void* lockSemaphore;
    std::uintptr_t spinCount;
};

struct virtualmodel_t
{
    studio_thread_fast_mutex_t m_Lock;
    studio_utlvector_t<virtualsequence_t> m_Sequence;
    studio_utlvector_t<virtualgeneric_t> m_Animation;
    studio_utlvector_t<virtualgeneric_t> m_Attachment;
    studio_utlvector_t<virtualgeneric_t> m_Pose;
    studio_utlvector_t<virtualgroup_t> m_Group;
    studio_utlvector_t<virtualgeneric_t> m_Node;
    studio_utlvector_t<virtualgeneric_t> m_IKLock;
    studio_utlvector_t<std::uint16_t> m_AutoplaySequences;
};
