#pragma once

#include "mathlib/vector.h"
#include "mathlib/mathlib.h"
#include "tier1/refcount.h"
#include "tier1/utlvector.h"
#include "tier1/utlhash.h"
#include "tier1/utlsymbol.h"

#include <cstddef>
#include <cstdint>
#include <type_traits>

inline constexpr std::uint32_t IDSTUDIOHEADER = 0x54534449u; // "IDST"
inline constexpr std::uint32_t MODEL_VERTEX_FILE_ID = 0x56534449u; // "IDSV"
inline constexpr std::int32_t MODEL_VERTEX_FILE_VERSION = 4;
inline constexpr std::uint32_t MODEL_VERTEX_COLOR_FILE_ID = 0x56434449u; // "IDCV"
inline constexpr std::int32_t MODEL_VERTEX_COLOR_FILE_VERSION = 1;
inline constexpr std::int32_t STUDIO_VERSION_TITANFALL2 = 53;
inline constexpr std::size_t MAX_NUM_LODS = 8;
inline constexpr std::size_t MAX_NUM_BONES_PER_VERT = 3;
inline constexpr std::size_t MAXSTUDIOBONES = 256;

enum StudioHeaderFlags : std::uint32_t
{
    STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 1u << 0,
    STUDIOHDR_FLAGS_USES_ENV_CUBEMAP = 1u << 1,
    STUDIOHDR_FLAGS_FORCE_OPAQUE = 1u << 2,
    STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS = 1u << 3,
    STUDIOHDR_FLAGS_STATIC_PROP = 1u << 4,
    STUDIOHDR_FLAGS_USES_FB_TEXTURE = 1u << 5,
    STUDIOHDR_FLAGS_HASSHADOWLOD = 1u << 6,
    STUDIOHDR_FLAGS_USES_BUMPMAPPING = 1u << 7,
    STUDIOHDR_FLAGS_USE_SHADOWLOD_MATERIALS = 1u << 8,
    STUDIOHDR_FLAGS_OBSOLETE = 1u << 9,
    STUDIOHDR_FLAGS_NEEDS_DEFERRED_ADDITIVE = 1u << 10,
    STUDIOHDR_FLAGS_NO_FORCED_FADE = 1u << 11,
    STUDIOHDR_FLAGS_FORCE_PHONEME_CROSSFADE = 1u << 12,
    STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT = 1u << 13,
    STUDIOHDR_FLAGS_COMPLEX_WEIGHTS = 1u << 14,
    STUDIOHDR_FLAGS_BUILT_IN_PREVIEW_MODE = 1u << 15,
    STUDIOHDR_FLAGS_AMBIENT_BOOST = 1u << 16,
    STUDIOHDR_FLAGS_DO_NOT_CAST_SHADOWS = 1u << 17,
    STUDIOHDR_FLAGS_CAST_TEXTURE_SHADOWS = 1u << 18,
    STUDIOHDR_FLAGS_SUBDIVISION_SURFACE = 1u << 19,
    STUDIOHDR_FLAGS_NO_ANIM_EVENTS = 1u << 20,
    STUDIOHDR_FLAGS_VERT_ANIM_FIXED_POINT_SCALE = 1u << 21,
    STUDIOHDR_FLAGS_RESPAWN_UNKNOWN = 1u << 23,
    STUDIOHDR_FLAGS_USES_VERTEX_COLOR = 1u << 24,
    STUDIOHDR_FLAGS_USES_UV2 = 1u << 25,
};

struct studiohdr_t;
struct studiomeshgroup_t;
class IMaterial;

struct mstudiobone_t
{
    int sznameindex;
    const char* pszName() const { return reinterpret_cast<const char*>(this) + sznameindex; }
    int parent;
    int bonecontroller[6];
    Vector3D pos;
    Quaternion quat;
    RadianEuler rot;
    Vector3D scale;
    Vector3D posscale;
    Vector3D rotscale;
    Vector3D scalescale;
    matrix3x4_t poseToBone;
    Quaternion qAlignment;
    int flags;
    int proctype;
    int procindex;
    int physicsbone;
    int surfacepropidx;
    int contents;
    int surfacepropLookup;
    std::int16_t unkindex;
    std::int16_t unkcount;
    int unused[7];

    void* pProcedure() const
    {
        return procindex ? reinterpret_cast<std::uint8_t*>(const_cast<mstudiobone_t*>(this)) + procindex : nullptr;
    }
    const char* pszSurfaceProp() const { return reinterpret_cast<const char*>(this) + surfacepropidx; }
};

static_assert(sizeof(mstudiobone_t) == 0xF4);
static_assert(offsetof(mstudiobone_t, pos) == 0x20);
static_assert(offsetof(mstudiobone_t, quat) == 0x2C);
static_assert(offsetof(mstudiobone_t, scale) == 0x48);
static_assert(offsetof(mstudiobone_t, scalescale) == 0x6C);
static_assert(offsetof(mstudiobone_t, flags) == 0xB8);

struct mstudioattachment_t
{
    int sznameindex;
    const char* pszName() const { return reinterpret_cast<const char*>(this) + sznameindex; }
    unsigned int flags;
    int localbone;
    matrix3x4_t local;
    int unused[8];
};

struct mstudioposeparamdesc_t
{
    int sznameindex;
    const char* pszName() const { return reinterpret_cast<const char*>(this) + sznameindex; }
    int flags;
    float start;
    float end;
    float loop;
};

static_assert(sizeof(mstudioattachment_t) == 0x5C);
static_assert(sizeof(mstudioposeparamdesc_t) == 0x14);

struct mstudiolinearbone_t
{
    int numbones;
    int flagsindex;
    int parentindex;
    int posindex;
    int quatindex;
    int rotindex;
    int posetoboneindex;
    int posscaleindex;
    int rotscaleindex;
    int qalignmentindex;
    int unused[6];

    const int* pFlags(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const int*>(reinterpret_cast<const std::uint8_t*>(this) + flagsindex) + bone;
    }
    int flags(int bone) const { return *pFlags(bone); }
    const int* pParent(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const int*>(reinterpret_cast<const std::uint8_t*>(this) + parentindex) + bone;
    }
    const Vector3D* pPos(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const Vector3D*>(reinterpret_cast<const std::uint8_t*>(this) + posindex) + bone;
    }
    const Quaternion* pQuat(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const Quaternion*>(reinterpret_cast<const std::uint8_t*>(this) + quatindex) + bone;
    }
    const RadianEuler* pRot(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const RadianEuler*>(reinterpret_cast<const std::uint8_t*>(this) + rotindex) + bone;
    }
    const matrix3x4_t* pPoseToBone(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const matrix3x4_t*>(reinterpret_cast<const std::uint8_t*>(this) + posetoboneindex) + bone;
    }
    const Vector3D* pRotScale(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const Vector3D*>(reinterpret_cast<const std::uint8_t*>(this) + rotscaleindex) + bone;
    }
    const Quaternion* pQAlignment(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const Quaternion*>(reinterpret_cast<const std::uint8_t*>(this) + qalignmentindex) + bone;
    }
};

struct mstudiosrcbonetransform_t
{
    int sznameindex;
    const char* pszName() const { return reinterpret_cast<const char*>(this) + sznameindex; }
    matrix3x4_t pretransform;
    matrix3x4_t posttransform;
};

struct mstudiopertrivertex_t
{
    short x, y, z;
};

struct mstudiopertrihdr_t
{
    short version;
    short unk;
    Vector3D bbmin;
    Vector3D bbmax;
    int unused[8];
};

static_assert(sizeof(mstudiolinearbone_t) == 0x40);
static_assert(sizeof(mstudiosrcbonetransform_t) == 0x64);
static_assert(sizeof(mstudiopertrivertex_t) == 6);
static_assert(sizeof(mstudiopertrihdr_t) == 0x3C);

enum StudioSequenceFlags
{
    STUDIO_LOOPING = 0x0001,
    STUDIO_SNAP = 0x0002,
    STUDIO_DELTA = 0x0004,
    STUDIO_AUTOPLAY = 0x0008,
    STUDIO_POST = 0x0010,
    STUDIO_ALLZEROS = 0x0020,
    STUDIO_CYCLEPOSE = 0x0080,
    STUDIO_REALTIME = 0x0100,
    STUDIO_LOCAL = 0x0200,
    STUDIO_HIDDEN = 0x0400,
    STUDIO_OVERRIDE = 0x0800,
    STUDIO_ACTIVITY = 0x1000,
    STUDIO_EVENT = 0x2000,
    STUDIO_WORLD = 0x4000,
    STUDIO_NOFORCELOOP = 0x8000,
    STUDIO_EVENT_CLIENT = 0x10000,
    STUDIO_FRAMEMOVEMENT = 0x40000
};

enum StudioAutolayerFlags
{
    STUDIO_AL_POST = 0x0010,
    STUDIO_AL_SPLINE = 0x0040,
    STUDIO_AL_XFADE = 0x0080,
    STUDIO_AL_NOBLEND = 0x0200,
    STUDIO_AL_LOCAL = 0x1000,
    STUDIO_AL_POSE = 0x4000
};

struct mstudioevent_t
{
    float cycle;
    union
    {
        int event;
        std::uint16_t event_newsystem;
    };
    int type;
    char options[64];
    int szeventindex;

    int Event() const { return (type & 0x400) ? event_newsystem : event; }
    void SetEvent(int value)
    {
        if (type & 0x400)
            event_newsystem = static_cast<std::uint16_t>(value);
        else
            event = value;
    }
    const char* pszOptions() const { return options; }
    const char* pszEventName() const { return reinterpret_cast<const char*>(this) + szeventindex; }
};

struct mstudioautolayer_t
{
    short iSequence;
    short iPose;
    int flags;
    float start;
    float peak;
    float tail;
    float end;
};

struct mstudioiklock_t
{
    int chain;
    float flPosWeight;
    float flLocalQWeight;
    int flags;
    int unused[4];
};

struct mstudioactivitymodifier_t
{
    int sznameindex;
    bool negate;

    const char* pszName() const
    {
        return sznameindex ? reinterpret_cast<const char*>(this) + sznameindex : nullptr;
    }
};

struct mstudioseqdesc_t
{
    int baseptr;
    int szlabelindex;
    int szactivitynameindex;
    int flags;
    int activity;
    int actweight;
    int numevents;
    int eventindex;
    Vector3D bbmin;
    Vector3D bbmax;
    int numblends;
    int animindexindex;
    int movementindex;
    int groupsize[2];
    int paramindex[2];
    float paramstart[2];
    float paramend[2];
    int paramparent;
    float fadeintime;
    float fadeouttime;
    int localentrynode;
    int localexitnode;
    int nodeflags;
    float entryphase;
    float exitphase;
    float lastframe;
    int nextseq;
    int pose;
    int numikrules;
    int numautolayers;
    int autolayerindex;
    int weightlistindex;
    int posekeyindex;
    int numiklocks;
    int iklockindex;
    int keyvalueindex;
    int keyvaluesize;
    int cycleposeindex;
    int activitymodifierindex;
    int numactivitymodifiers;
    int ikResetMask;
    int cycleGroup;
    int unused[8];

    studiohdr_t* pStudiohdr() const
    {
        return reinterpret_cast<studiohdr_t*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + baseptr);
    }
    const char* pszLabel() const { return reinterpret_cast<const char*>(this) + szlabelindex; }
    const char* pszActivityName() const { return reinterpret_cast<const char*>(this) + szactivitynameindex; }
    mstudioevent_t* pEvent(int i) const
    {
        Assert(i >= 0 && i < numevents);
        return reinterpret_cast<mstudioevent_t*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + eventindex) + i;
    }
    int anim(int x, int y) const
    {
        if (x >= groupsize[0])
            x = groupsize[0] - 1;
        if (y >= groupsize[1])
            y = groupsize[1] - 1;
        return reinterpret_cast<const short*>(reinterpret_cast<const std::uint8_t*>(this) + animindexindex)[y * groupsize[0] + x];
    }
    mstudioautolayer_t* pAutolayer(int i) const
    {
        Assert(i >= 0 && i < numautolayers);
        return reinterpret_cast<mstudioautolayer_t*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + autolayerindex) + i;
    }
    float* pBoneweight(int i) const
    {
        return reinterpret_cast<float*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + weightlistindex) + i;
    }
    float weight(int i) const { return *pBoneweight(i); }
    float* pPoseKey(int parameter, int animation) const
    {
        return reinterpret_cast<float*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + posekeyindex)
            + parameter * groupsize[0] + animation;
    }
    float poseKey(int parameter, int animation) const { return *pPoseKey(parameter, animation); }
    mstudioiklock_t* pIKLock(int i) const
    {
        Assert(i >= 0 && i < numiklocks);
        return reinterpret_cast<mstudioiklock_t*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + iklockindex) + i;
    }
    const char* KeyValueText() const
    {
        return keyvaluesize ? reinterpret_cast<const char*>(this) + keyvalueindex : nullptr;
    }
    mstudioactivitymodifier_t* pActivityModifier(int i) const
    {
        Assert(i >= 0 && i < numactivitymodifiers);
        return activitymodifierindex
            ? reinterpret_cast<mstudioactivitymodifier_t*>(reinterpret_cast<std::uint8_t*>(const_cast<mstudioseqdesc_t*>(this)) + activitymodifierindex) + i
            : nullptr;
    }

    mstudioseqdesc_t() = default;
private:
    mstudioseqdesc_t(const mstudioseqdesc_t&) = delete;
};

struct mstudiotexture_t
{
    std::int32_t sznameindex;
    std::int32_t unused_flags;
    std::int32_t used;
    std::int32_t unused[8];

    const char* Name() const noexcept
    {
        return sznameindex > 0 ? reinterpret_cast<const char*>(this) + sznameindex : "";
    }
};

struct mstudio_meshvertexdata_t
{
    std::int32_t modelvertexdata;
    std::int32_t numLODVertexes[MAX_NUM_LODS];
};

#pragma pack(push, 4)
struct mstudiomesh_t
{
    std::int32_t material;
    std::int32_t modelindex;
    std::int32_t numvertices;
    std::int32_t vertexoffset;
    std::int32_t deprecated_numflexes;
    std::int32_t deprecated_flexindex;
    std::int32_t deprecated_materialtype;
    std::int32_t deprecated_materialparam;
    std::int32_t meshid;
    Vector3D center;
    mstudio_meshvertexdata_t vertexloddata;
    void* pUnknown;
    std::int32_t reserved[6];
};
#pragma pack(pop)

struct mstudiomodel_t
{
    char name[64];
    std::int32_t type;
    float boundingradius;
    std::int32_t nummeshes;
    std::int32_t meshindex;
    std::int32_t numvertices;
    std::int32_t vertexindex;
    std::int32_t tangentsindex;
    std::int32_t numattachments;
    std::int32_t attachmentindex;
    std::int32_t deprecated_numeyeballs;
    std::int32_t deprecated_eyeballindex;
    std::int32_t pad[4];
    std::int32_t colorindex;
    std::int32_t uv2index;
    std::int32_t reserved[4];

    const mstudiomesh_t* Mesh(std::size_t index) const noexcept
    {
        if (nummeshes <= 0 || index >= static_cast<std::size_t>(nummeshes) || meshindex <= 0)
            return nullptr;
        return reinterpret_cast<const mstudiomesh_t*>(reinterpret_cast<const std::uint8_t*>(this) + meshindex) + index;
    }
};

struct mstudiobodyparts_t
{
    std::int32_t sznameindex;
    std::int32_t nummodels;
    std::int32_t base;
    std::int32_t modelindex;

    const char* Name() const noexcept
    {
        return sznameindex > 0 ? reinterpret_cast<const char*>(this) + sznameindex : "";
    }

    const mstudiomodel_t* Model(std::size_t index) const noexcept
    {
        if (nummodels <= 0 || index >= static_cast<std::size_t>(nummodels) || modelindex <= 0)
            return nullptr;
        return reinterpret_cast<const mstudiomodel_t*>(reinterpret_cast<const std::uint8_t*>(this) + modelindex) + index;
    }
};

struct studiohdr_t
{
    std::int32_t id;
    std::int32_t version;
    std::int32_t checksum;
    std::int32_t sznameindex;
    char name[64];
    std::int32_t length;
    Vector3D eyeposition;
    Vector3D illumposition;
    Vector3D hull_min;
    Vector3D hull_max;
    Vector3D view_bbmin;
    Vector3D view_bbmax;
    std::uint32_t flags;
    std::int32_t numbones;
    std::int32_t boneindex;
    std::int32_t numbonecontrollers;
    std::int32_t bonecontrollerindex;
    std::int32_t numhitboxsets;
    std::int32_t hitboxsetindex;
    std::int32_t numlocalanim;
    std::int32_t localanimindex;
    std::int32_t numlocalseq;
    std::int32_t localseqindex;
    std::int32_t activitylistversion;
    std::int32_t eventsindexed;
    std::int32_t numtextures;
    std::int32_t textureindex;
    std::int32_t numcdtextures;
    std::int32_t cdtextureindex;
    std::int32_t numskinref;
    std::int32_t numskinfamilies;
    std::int32_t skinindex;
    std::int32_t numbodyparts;
    std::int32_t bodypartindex;
    std::int32_t numlocalattachments;
    std::int32_t localattachmentindex;
    std::int32_t numlocalnodes;
    std::int32_t localnodeindex;
    std::int32_t localnodenameindex;
    std::int32_t deprecated_numflexdesc;
    std::int32_t deprecated_flexdescindex;
    std::int32_t deprecated_numflexcontrollers;
    std::int32_t deprecated_flexcontrollerindex;
    std::int32_t deprecated_numflexrules;
    std::int32_t deprecated_flexruleindex;
    std::int32_t numikchains;
    std::int32_t ikchainindex;
    std::int32_t uiPanelCount;
    std::int32_t uiPanelOffset;
    std::int32_t numlocalposeparameters;
    std::int32_t localposeparamindex;
    std::int32_t surfacepropindex;
    std::int32_t keyvalueindex;
    std::int32_t keyvaluesize;
    std::int32_t numlocalikautoplaylocks;
    std::int32_t localikautoplaylockindex;
    float mass;
    std::int32_t contents;
    std::int32_t numincludemodels;
    std::int32_t includemodelindex;
    std::int32_t virtualModel;
    std::int32_t bonetablebynameindex;
    std::uint8_t constdirectionallightdot;
    std::uint8_t rootLOD;
    std::uint8_t numAllowedRootLODs;
    std::uint8_t unused;
    float defaultFadeDist;
    std::int32_t deprecated_numflexcontrollerui;
    std::int32_t deprecated_flexcontrolleruiindex;
    float flVertAnimFixedPointScale;
    std::int32_t surfacepropLookup;
    std::int32_t sourceFilenameOffset;
    std::int32_t numsrcbonetransform;
    std::int32_t srcbonetransformindex;
    std::int32_t illumpositionattachmentindex;
    std::int32_t linearboneindex;
    std::int32_t m_nBoneFlexDriverCount;
    std::int32_t m_nBoneFlexDriverIndex;
    std::int32_t m_nPerTriAABBIndex;
    std::int32_t m_nPerTriAABBNodeCount;
    std::int32_t m_nPerTriAABBLeafCount;
    std::int32_t m_nPerTriAABBVertCount;
    std::int32_t unkStringOffset;
    std::int32_t vtxOffset;
    std::int32_t vvdOffset;
    std::int32_t vvcOffset;
    std::int32_t phyOffset;
    std::int32_t vtxSize;
    std::int32_t vvdSize;
    std::int32_t vvcSize;
    std::int32_t phySize;
    std::int32_t unkOffset;
    std::int32_t unkCount;
    std::int32_t boneFollowerCount;
    std::int32_t boneFollowerOffset;
    std::int32_t unused1[60];

    const char* pszName() const noexcept
    {
        return sznameindex ? reinterpret_cast<const char*>(this) + sznameindex : nullptr;
    }
    const char* Name() const noexcept { return pszName(); }
    const mstudiobone_t* pBone(int bone) const
    {
        Assert(bone >= 0 && bone < numbones);
        return reinterpret_cast<const mstudiobone_t*>(reinterpret_cast<const std::uint8_t*>(this) + boneindex) + bone;
    }
    const std::uint8_t* GetBoneTableSortedByName() const
    {
        return reinterpret_cast<const std::uint8_t*>(this) + bonetablebynameindex;
    }
    const char* pszSurfaceProp() const
    {
        return reinterpret_cast<const char*>(this) + surfacepropindex;
    }
    const char* KeyValueText() const
    {
        return keyvaluesize ? reinterpret_cast<const char*>(this) + keyvalueindex : nullptr;
    }
    const int* pBoneFollowers(int index) const
    {
        Assert(index >= 0 && index < boneFollowerCount);
        return reinterpret_cast<const int*>(reinterpret_cast<const std::uint8_t*>(this) + boneFollowerOffset) + index;
    }
    int BoneFollower(int index) const { return *pBoneFollowers(index); }
    const mstudiolinearbone_t* pLinearBones() const
    {
        return linearboneindex ? reinterpret_cast<const mstudiolinearbone_t*>(
            reinterpret_cast<const std::uint8_t*>(this) + linearboneindex) : nullptr;
    }
    const mstudiosrcbonetransform_t* SrcBoneTransform(int index) const
    {
        Assert(index >= 0 && index < numsrcbonetransform);
        return reinterpret_cast<const mstudiosrcbonetransform_t*>(
            reinterpret_cast<const std::uint8_t*>(this) + srcbonetransformindex) + index;
    }
    const mstudiopertrihdr_t* pPerTriHdr() const
    {
        return m_nPerTriAABBIndex ? reinterpret_cast<const mstudiopertrihdr_t*>(
            reinterpret_cast<const std::uint8_t*>(this) + m_nPerTriAABBIndex) : nullptr;
    }
    mstudioseqdesc_t& pLocalSeqdesc(int sequence) const
    {
        if (sequence < 0 || sequence >= numlocalseq)
            sequence = 0;
        return *(reinterpret_cast<mstudioseqdesc_t*>(
            reinterpret_cast<std::uint8_t*>(const_cast<studiohdr_t*>(this)) + localseqindex) + sequence);
    }
    const mstudioattachment_t& pLocalAttachment(int attachment) const
    {
        Assert(attachment >= 0 && attachment < numlocalattachments);
        return *(reinterpret_cast<const mstudioattachment_t*>(
            reinterpret_cast<const std::uint8_t*>(this) + localattachmentindex) + attachment);
    }
    const mstudioposeparamdesc_t& pLocalPoseParameter(int parameter) const
    {
        Assert(parameter >= 0 && parameter < numlocalposeparameters);
        return *(reinterpret_cast<const mstudioposeparamdesc_t*>(
            reinterpret_cast<const std::uint8_t*>(this) + localposeparamindex) + parameter);
    }
    const mstudioiklock_t& pLocalIKAutoplayLock(int lock) const
    {
        Assert(lock >= 0 && lock < numlocalikautoplaylocks);
        return *(reinterpret_cast<const mstudioiklock_t*>(
            reinterpret_cast<const std::uint8_t*>(this) + localikautoplaylockindex) + lock);
    }


    const char* SourceFilename() const noexcept
    {
        return sourceFilenameOffset ? reinterpret_cast<const char*>(this) + sourceFilenameOffset : nullptr;
    }

    const mstudiotexture_t* Texture(std::size_t index) const noexcept
    {
        if (numtextures <= 0 || index >= static_cast<std::size_t>(numtextures) || textureindex <= 0 || length < 0)
            return nullptr;
        const auto offset = static_cast<std::size_t>(textureindex);
        const auto bytes = static_cast<std::size_t>(length);
        const auto remaining = bytes >= offset ? bytes - offset : 0;
        if (index >= remaining / sizeof(mstudiotexture_t))
            return nullptr;
        return reinterpret_cast<const mstudiotexture_t*>(reinterpret_cast<const std::uint8_t*>(this) + offset) + index;
    }

    const mstudiobodyparts_t* BodyPart(std::size_t index) const noexcept
    {
        if (numbodyparts <= 0 || index >= static_cast<std::size_t>(numbodyparts) || bodypartindex <= 0 || length < 0)
            return nullptr;
        const auto offset = static_cast<std::size_t>(bodypartindex);
        const auto bytes = static_cast<std::size_t>(length);
        const auto remaining = bytes >= offset ? bytes - offset : 0;
        if (index >= remaining / sizeof(mstudiobodyparts_t))
            return nullptr;
        return reinterpret_cast<const mstudiobodyparts_t*>(reinterpret_cast<const std::uint8_t*>(this) + offset) + index;
    }
};

struct mstudio_boneweight_t
{
    float weight[MAX_NUM_BONES_PER_VERT];
    std::uint8_t bone[MAX_NUM_BONES_PER_VERT];
    std::uint8_t numbones;
};

struct mstudiovertex_t
{
    mstudio_boneweight_t m_BoneWeights;
    Vector3D m_vecPosition;
    Vector3D m_vecNormal;
    Vector2D m_vecTexCoord;
};

struct vertexFileFixup_t
{
    std::int32_t lod;
    std::int32_t sourceVertexID;
    std::int32_t numVertexes;
};

struct vertexFileHeader_t
{
    std::uint32_t id;
    std::int32_t version;
    std::int32_t checksum;
    std::int32_t numLODs;
    std::int32_t numLODVertexes[MAX_NUM_LODS];
    std::int32_t numFixups;
    std::int32_t fixupTableStart;
    std::int32_t vertexDataStart;
    std::int32_t tangentDataStart;

    std::size_t VertexCount(std::size_t lod = 0) const noexcept
    {
        if (numLODs <= 0 || lod >= MAX_NUM_LODS || lod >= static_cast<std::size_t>(numLODs) || numLODVertexes[lod] < 0)
            return 0;
        return static_cast<std::size_t>(numLODVertexes[lod]);
    }

    const vertexFileFixup_t* Fixup(std::size_t index) const noexcept
    {
        if (numFixups <= 0 || index >= static_cast<std::size_t>(numFixups) || fixupTableStart <= 0)
            return nullptr;
        return reinterpret_cast<const vertexFileFixup_t*>(reinterpret_cast<const std::uint8_t*>(this) + fixupTableStart) + index;
    }

    const mstudiovertex_t* Vertex(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || vertexDataStart <= 0)
            return nullptr;
        return reinterpret_cast<const mstudiovertex_t*>(reinterpret_cast<const std::uint8_t*>(this) + vertexDataStart) + index;
    }

    const float* Tangent(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || tangentDataStart <= 0)
            return nullptr;
        return reinterpret_cast<const float*>(reinterpret_cast<const std::uint8_t*>(this) + tangentDataStart) + index * 4;
    }
};

struct studio_color32_t
{
    std::uint8_t r;
    std::uint8_t g;
    std::uint8_t b;
    std::uint8_t a;
};

struct vertexColorFileHeader_t
{
    std::uint32_t id;
    std::int32_t version;
    std::int32_t checksum;
    std::int32_t numLODs;
    std::int32_t numLODVertexes[MAX_NUM_LODS];
    std::int32_t colorDataStart;
    std::int32_t uv2DataStart;

    std::size_t VertexCount(std::size_t lod = 0) const noexcept
    {
        if (numLODs <= 0 || lod >= MAX_NUM_LODS || lod >= static_cast<std::size_t>(numLODs) || numLODVertexes[lod] < 0)
            return 0;
        return static_cast<std::size_t>(numLODVertexes[lod]);
    }

    const studio_color32_t* Color(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || colorDataStart <= 0)
            return nullptr;
        return reinterpret_cast<const studio_color32_t*>(reinterpret_cast<const std::uint8_t*>(this) + colorDataStart) + index;
    }

    const Vector2D* SecondaryUV(std::size_t index) const noexcept
    {
        if (index >= VertexCount() || uv2DataStart <= 0)
            return nullptr;
        return reinterpret_cast<const Vector2D*>(reinterpret_cast<const std::uint8_t*>(this) + uv2DataStart) + index;
    }
};

struct studiomeshdata_t
{
    std::int32_t m_NumGroup;
    std::uint32_t reservedAlignment;
    studiomeshgroup_t* m_pMeshGroup;
};

struct studioloddata_t
{
    studiomeshdata_t* m_pMeshData;
    float m_SwitchPoint;
    std::int32_t m_NumMaterials;
    IMaterial** m_ppMaterials;
    std::int32_t* m_pMaterialFlags;
    std::int32_t* m_pHWMorphDecalBoneRemap;
    std::int32_t m_DecalBoneCount;
    std::uint32_t reservedAlignment;
};

struct studiohwdata_t
{
    std::int32_t m_RootLOD;
    std::int32_t m_NumLODs;
    studioloddata_t* m_pLODs;
    std::int32_t m_NumStudioMeshes;
    std::int32_t m_NumVertices;
    std::uint8_t* m_pVertexRemap;

    const studioloddata_t* LOD(std::size_t index) const noexcept
    {
        return m_pLODs != nullptr && m_NumLODs > 0 && index < static_cast<std::size_t>(m_NumLODs)
            ? m_pLODs + index
            : nullptr;
    }
};

template <class T>
class CStudioAssetEmbeddedRef : public CRefCounted<>
{
  protected:
    T m_Embedded;
};

class CStudioHWDataRef : public CStudioAssetEmbeddedRef<studiohwdata_t>
{
  public:
    studiohwdata_t* GetHardwareData() noexcept { return &m_Embedded; }
    const studiohwdata_t* GetHardwareData() const noexcept { return &m_Embedded; }
};


struct virtualsequence_t
{
    std::int32_t flags;
    std::int32_t activity;
    std::int32_t group;
    std::int32_t index;
};

struct virtualgeneric_t
{
    std::int32_t group;
    std::int32_t index;
};

struct virtualgroup_t
{
    virtualgroup_t() : cache(nullptr) {}
    void* cache;
    const studiohdr_t* GetStudioHdr() const;
    CUtlVector<int> boneMap;
    CUtlVector<int> masterBone;
    CUtlVector<int> masterSeq;
    CUtlVector<int> masterAnim;
    CUtlVector<int> masterAttachment;
    CUtlVector<int> masterPose;
    CUtlVector<int> masterNode;
};


struct virtualmodel_t
{
    CUtlVector<virtualsequence_t> m_seq;
    CUtlVector<virtualgeneric_t> m_anim;
    CUtlVector<virtualgeneric_t> m_pose;
    CUtlVector<virtualgroup_t> m_group;
    CUtlVector<virtualgeneric_t> m_node;
    CUtlVector<virtualgeneric_t> m_iklock;
    CUtlVector<unsigned short> m_autoplaySequences;

    virtualgroup_t* pAnimGroup(int animation) { return &m_group[m_anim[animation].group]; }
    virtualgroup_t* pSeqGroup(int sequence)
    {
        if (static_cast<unsigned int>(sequence) >= static_cast<unsigned int>(m_seq.Count()))
        {
            Assert(false);
            return nullptr;
        }
        return &m_group[m_seq[sequence].group];
    }

    void AppendSequences(int group, const studiohdr_t* studioHdr);
    void AppendAnimations(int group, const studiohdr_t* studioHdr);
    void AppendPoseParameters(int group, const studiohdr_t* studioHdr);
    void AppendBonemap(int group, const studiohdr_t* studioHdr);
    void AppendNodes(int group, const studiohdr_t* studioHdr);
    void AppendIKLocks(int group, const studiohdr_t* studioHdr);
    void AppendModels(int group, const studiohdr_t* studioHdr);
};

static_assert(sizeof(virtualsequence_t) == 0x10);
static_assert(sizeof(virtualgeneric_t) == 8);
static_assert(sizeof(virtualgroup_t) == 0xE8);
static_assert(offsetof(virtualgroup_t, masterSeq) == 0x48);
static_assert(offsetof(virtualgroup_t, masterPose) == 0xA8);
static_assert(sizeof(virtualmodel_t) == 0xE0);
static_assert(offsetof(virtualmodel_t, m_seq) == 0);
static_assert(offsetof(virtualmodel_t, m_anim) == 0x20);
static_assert(offsetof(virtualmodel_t, m_pose) == 0x40);
static_assert(offsetof(virtualmodel_t, m_group) == 0x60);
static_assert(offsetof(virtualmodel_t, m_node) == 0x80);
static_assert(offsetof(virtualmodel_t, m_iklock) == 0xA0);
static_assert(offsetof(virtualmodel_t, m_autoplaySequences) == 0xC0);

class IMDLCache;

class CStudioHdr
{
public:
    CStudioHdr();
    explicit CStudioHdr(const studiohdr_t* studioHdr, IMDLCache* mdlcache = nullptr);
    ~CStudioHdr();
    void Init(const studiohdr_t* studioHdr, IMDLCache* mdlcache = nullptr);
    void Term();

    bool IsVirtual() const { return m_pVModel != nullptr; }
    bool IsValid() const { return m_pStudioHdr != nullptr; }
    bool IsReadyForAccess() const { return m_pStudioHdr != nullptr; }
    virtualmodel_t* GetVirtualModel() const { return m_pVModel; }
    const studiohdr_t* GetRenderHdr() const { return m_pStudioHdr; }
    const studiohdr_t* pSeqStudioHdr(int sequence);
    const studiohdr_t* pAnimStudioHdr(int animation);
    const virtualmodel_t* ResetVModel(const virtualmodel_t* virtualModel) const;

    int numbones() const { return m_pStudioHdr->numbones; }
    mstudiobone_t* pBone(int bone) const;
    int boneFlags(int bone) const { return m_boneFlags[bone]; }
    int boneParent(int bone) const { return m_boneParent[bone]; }

    bool SequencesAvailable() const;
    int GetNumSeq() const;
    mstudioseqdesc_t& pSeqdesc(int sequence);
    int iRelativeAnim(int baseSequence, int relativeAnimation) const;
    int iRelativeSeq(int baseSequence, int relativeSequence) const;
    int GetActivityListVersion();
    void SetActivityListVersion(int version);
    int GetEventListVersion();
    void SetEventListVersion(int version);

    int GetNumAttachments() const;
    const mstudioattachment_t& pAttachment(int attachment);
    int GetAttachmentBone(int attachment);
    int EntryNode(int sequence);
    int ExitNode(int sequence);
    const char* pszNodeName(int node);
    int GetTransition(int from, int to) const;

    int GetNumPoseParameters() const;
    const mstudioposeparamdesc_t& pPoseParameter(int parameter);
    int GetSharedPoseParameter(int sequence, int localPose) const;
    int GetNumIKAutoplayLocks() const;
    const mstudioiklock_t& pIKAutoplayLock(int lock);
    int GetAutoplayList(unsigned short** sequences) const;

    int GetNumBoneControllers() const { return m_pStudioHdr->numbonecontrollers; }
    int numbonecontrollers() const { return m_pStudioHdr->numbonecontrollers; }
    int numikchains() const { return m_pStudioHdr->numikchains; }
    int GetNumIKChains() const { return m_pStudioHdr->numikchains; }
    const char* pszName() const { return m_pStudioHdr->Name(); }
    int numhitboxsets() const { return m_pStudioHdr->numhitboxsets; }
    int numbodyparts() const { return m_pStudioHdr->numbodyparts; }
    int numskinfamilies() const { return m_pStudioHdr->numskinfamilies; }
    int numtextures() const { return m_pStudioHdr->numtextures; }
    Vector3D eyeposition() const { return m_pStudioHdr->eyeposition; }
    int flags() const { return m_pStudioHdr->flags; }
    float mass() const { return m_pStudioHdr->mass; }
    int contents() const { return m_pStudioHdr->contents; }
    Vector3D illumposition() const { return m_pStudioHdr->illumposition; }
    Vector3D hull_min() const { return m_pStudioHdr->hull_min; }
    Vector3D hull_max() const { return m_pStudioHdr->hull_max; }
    Vector3D view_bbmin() const { return m_pStudioHdr->view_bbmin; }
    Vector3D view_bbmax() const { return m_pStudioHdr->view_bbmax; }
    const std::uint8_t* GetBoneTableSortedByName() const
    {
        return reinterpret_cast<const std::uint8_t*>(m_pStudioHdr) + m_pStudioHdr->bonetablebynameindex;
    }
    const char* pszSurfaceProp() const
    {
        return reinterpret_cast<const char*>(m_pStudioHdr) + m_pStudioHdr->surfacepropindex;
    }

    class CActivityToSequenceMapping
    {
    public:
        struct ActivityModifier
        {
            CUtlSymbol symbol;
            bool negate;
        };
        struct SequenceTuple
        {
            short seqnum;
            short weight;
            ActivityModifier* pActivityModifiers;
            int iNumActivityModifiers;
        };
        struct HashValueType
        {
            int activityIdx;
            int startingIdx;
            int count;
            int totalWeight;
            HashValueType(int activity, int start, int sequenceCount, int weight)
                : activityIdx(activity), startingIdx(start), count(sequenceCount), totalWeight(weight) {}
            HashValueType() : activityIdx(-1), startingIdx(-1), count(-1), totalWeight(-1) {}
            struct HashFuncs
            {
                HashFuncs(int) {}
                bool operator()(const HashValueType& lhs, const HashValueType& rhs) const
                {
                    return lhs.activityIdx == rhs.activityIdx;
                }
                unsigned int operator()(const HashValueType& value) const;
            };
        };
        using ActivityToValueIdxHash = CUtlHash<HashValueType, HashValueType::HashFuncs, HashValueType::HashFuncs>;

        CActivityToSequenceMapping();
        ~CActivityToSequenceMapping();
        CActivityToSequenceMapping(const CActivityToSequenceMapping&) = delete;
        CActivityToSequenceMapping& operator=(const CActivityToSequenceMapping&) = delete;
        const SequenceTuple* GetSequences(int activity, int* sequenceCount, int* totalWeight);
        int NumSequencesForActivity(int activity);
        static CActivityToSequenceMapping* FindMapping(CStudioHdr* studioHdr);
        static void ReleaseMapping(CActivityToSequenceMapping* mapping);
        static void ResetUnusedMappings();

    private:
        void Initialize(CStudioHdr* studioHdr);
        void Reinitialize(CStudioHdr* studioHdr);
        bool ValidateAgainst(const CStudioHdr* studioHdr) const;
        void SetValidationPair(const CStudioHdr* studioHdr);
        int SelectWeightedSequence(CStudioHdr* studioHdr, int activity, bool useModifiers,
            const CUtlSymbol* modifiers, int modifierCount, int currentSequence);
        SequenceTuple* m_pSequenceTuples;
        unsigned int m_iSequenceTuplesCount;
        ActivityToValueIdxHash m_ActToSeqHash;
        const studiohdr_t* m_pStudioHdr;
        const virtualmodel_t* m_expectedVModel;
        friend class CStudioHdr;
    };

    CActivityToSequenceMapping* GetActivityToSequenceMapping();
    int SelectWeightedSequence(int activity, int currentSequence);
    int SelectWeightedSequence(int activity, bool useModifiers, const CUtlSymbol* modifiers,
        int modifierCount, int currentSequence);
    int SelectWeightedSequenceFromModifiers(int activity, const CUtlSymbol* modifiers, int modifierCount);
    bool HaveSequenceForActivity(int activity);
    void ReinitializeSequenceMapping();

private:
    const studiohdr_t* GroupStudioHdr(int group);

    unsigned int m_uniqueId;
    mutable const studiohdr_t* m_pStudioHdr;
    mutable virtualmodel_t* m_pVModel;
    mutable CUtlVector<const studiohdr_t*> m_pStudioHdrCache;
    mutable int m_nFrameUnlockCounter;
    int* m_pFrameUnlockCounter;
    int m_boneFlags[MAXSTUDIOBONES];
    int m_boneParent[MAXSTUDIOBONES];
    CActivityToSequenceMapping* m_pActivityToSequence;

public:
    void ClearPerfCounters()
    {
        m_nPerfAnimatedBones = 0;
        m_nPerfUsedBones = 0;
        m_nPerfAnimationLayers = 0;
    }
    mutable int m_nPerfAnimatedBones;
    mutable int m_nPerfUsedBones;
    mutable int m_nPerfAnimationLayers;
};
