name: CI
on: [push, pull_request]

env:
  BUILD_PROFILE: Release
  NORTHSTAR_VERSION: 0.0.0.${{github.run_number}}
  NS_BINARY_OUTPUT: ${{ github.workspace }}/build/game

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        config:
          - { name: "MSVC", cc: cl }
          - { name: "LLVM", cc: clang-cl  }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Checkout EOS SDK
        uses: actions/checkout@v4
        with:
          repository: r2ion/eos-ion
          token: ${{ secrets.EOS_PAT_TOKEN  }}
          path: src/thirdparty/eossdk
      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compute CMake version values
        shell: bash
        run: |
          VERSION_TEXT="${{ env.NORTHSTAR_VERSION }}"
          VERSION_NUMERIC=$(echo "${VERSION_TEXT}" | sed -E 's/-rc[0-9]+//' | tr '.' ',' | tr -cd '0-9,')
          echo "NS_VERSION_STRING=${VERSION_TEXT}" >> $GITHUB_ENV
          echo "NS_VERSION_NUMERIC=${VERSION_NUMERIC}" >> $GITHUB_ENV
          echo "NS_ION_PATCH=0" >> $GITHUB_ENV
      - name: Configure cmake
        shell: bash
        run: >
          cmake -G "Ninja" -B build
          -DNS_BINARY_DIR:PATH="${{ env.NS_BINARY_OUTPUT }}"
          -DNS_PUBLISH_LAUNCHER:BOOL=ON
          -DNS_VERSION_NUMERIC:STRING="$NS_VERSION_NUMERIC"
          -DNS_VERSION_STRING:STRING="$NS_VERSION_STRING"
          -DNS_ION_PATCH:STRING="$NS_ION_PATCH"
      - name: Build
        run: cmake --build build/ --config "${{ env.BUILD_PROFILE }}"
      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NorthstarLauncher-${{ matrix.config.name }}-${{ steps.extract.outputs.commit }}
          path: |
            ${{ env.NS_BINARY_OUTPUT }}/

# can someone fix this i swear to god
#   format-check:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: DoozyX/clang-format-lint-action@v0.20
#       with:
#         source: 'src include proxy dedicated'
#         exclude: 'src/thirdparty'
#         extensions: 'h,cpp'
#         clangFormatVersion: 20
#         inplace: true
#         style: file

  format-check-cmake-files:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: puneetmatharu/cmake-format-lint-action@v1.0.4
      with:
        args: "--in-place"
    - run: |
        git diff --exit-code
