name: Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

env:
  NORTHSTAR_VERSION: ${{ github.ref_name }}
  NS_BINARY_OUTPUT: ${{ github.workspace }}/build/game

jobs:
  build-launcher:
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Checkout EOS SDK
        uses: actions/checkout@v4
        with:
          repository: r2ion/eos-ion
          token: ${{ secrets.EOS_PAT_TOKEN  }}
          path: src/thirdparty/eossdk
      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compute CMake version values
        shell: bash
        run: |
          VERSION_FULL=$(echo "${{ env.NORTHSTAR_VERSION }}" | sed 's/^v//')
          VERSION_BASE=$(echo "${VERSION_FULL}" | cut -d'_' -f1)
          PATCH_VERSION=$(echo "${VERSION_FULL}" | cut -d'_' -f2)

          if [[ "${VERSION_FULL}" == "${PATCH_VERSION}" ]]; then
            PATCH_VERSION=0
          fi

          VERSION_NUMERIC=$(echo "${VERSION_BASE}" | tr '.' ',')

          echo "NS_VERSION_STRING=${{ env.NORTHSTAR_VERSION }}" >> $GITHUB_ENV
          echo "NS_VERSION_NUMERIC=${VERSION_NUMERIC}" >> $GITHUB_ENV
          echo "NS_ION_PATCH=${PATCH_VERSION}" >> $GITHUB_ENV
      - name: Configure cmake
        shell: bash
        run: >
          cmake -G "Visual Studio 18 2026" -A x64 -B build
          -DNS_BINARY_DIR:PATH="${{ env.NS_BINARY_OUTPUT }}"
          -DNS_PUBLISH_LAUNCHER:BOOL=ON
          -DNS_VERSION_NUMERIC:STRING="$NS_VERSION_NUMERIC"
          -DNS_VERSION_STRING:STRING="$NS_VERSION_STRING"
          -DNS_ION_PATCH:STRING="$NS_ION_PATCH"
      - name: Build
        run: cmake --build build/ --config Release
      - name: Upload launcher build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ion-launcher
          path: |
            ${{ env.NS_BINARY_OUTPUT }}/*.exe
            ${{ env.NS_BINARY_OUTPUT }}/*.dll
            ${{ env.NS_BINARY_OUTPUT }}/*.pdb
            ${{ env.NS_BINARY_OUTPUT }}/bin/x64_retail/*.dll
            ${{ env.NS_BINARY_OUTPUT }}/bin/x64_retail/*.pdb

  upload-launcher-to-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-launcher
    runs-on: ubuntu-22.04
    steps:
      - name: Download compiled launcher
        uses: actions/download-artifact@v4
        with:
          name: ion-launcher
          path: ion-launcher
      - name: Create zip with binaries
        run: |
          cd ion-launcher
          zip --recurse-paths --quiet ../ion-launcher.zip *
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        with:
          body: ":warning: These are development files! If you want to download Ion, [go here instead](https://github.com/sonny-tel/Ion/releases) :warning:"
          draft: false
          files: |
            ion-launcher.zip
